In [2]:
import numpy as np

In [1]:
print("Hello World")

Hello World


In [4]:
def helloworld():
    print("Sample Function")

helloworld()

Sample Function


In [6]:
from statistics import mean
values = [45,36,60]
print(mean(values))

47


In [9]:
import numpy as np
fluxes = np.array([23.3, 42.1, 2.0, -3.2, 55.6])
print(np.mean(fluxes))
print(np.std(fluxes))
print(np.size(fluxes))

23.96
22.585358088814974
5


In [13]:
data = []
for line in open('data.csv',encoding='utf8'):
  data.append(line.strip().split(','))

print(data)

[['8.84', '17.22', '13.22', '3.84'], ['3.99', '11.73', '19.66', '1.27'], ['16.14', '18.72', '7.43', '11.09']]


In [15]:
import numpy as np

data = np.loadtxt('data.csv', delimiter=',')
data = np.asarray(data, float)
print(data)

[[ 8.84 17.22 13.22  3.84]
 [ 3.99 11.73 19.66  1.27]
 [16.14 18.72  7.43 11.09]]


In [16]:
(np.round(np.mean(data),1),np.round(np.median(data),1))

(11.1, 11.4)

In [17]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise multiplication 
print(a*2)

# Element-wise summation 
print(a + b)

# Element-wise product 
print(a*b)

[2 4 6]
[5 7 9]
[ 4 10 18]


In [18]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]])  # 2x3 array

# Print first row of a:
print(a[0,:])

# Print second column of a:
print(a[:,1])

[1 2 3]
[2 5]


In [19]:
a = np.array({'B1':0}, {'B2': 0}, dtype=object)
#a[0]['B3']=1
print(a)

TypeError: Argument given by name ('dtype') and position (2)